### ISSUE TITLE
Erreurs entre le diagramme et la conf ESPHome?

### ISSUE THREAD

**Issue by alucryd** [xmow49/teleinfo-esphome-homeassistant#10]
Bonjour, j'essaie de monter le petit circuit électronique chez moi, malheureusement je n'ai pas de données qui remontent dans home assistant, et je ne vois rien dans les logs en debug, pourtant je ne pense pas m’être trompé.

Deux choses me semblent bizarres dans le diagramme:

- le pin D7 est utilisé (a priori GPIO13) mais dans la config c'est GPIO3 qui est présent (du coup RX sur le D1), est-ce une erreur ? je n'ai pas de données avec l'un ou l'autre mais j'aimerais être sur
- ~~le pin 5V est utilisé sur le diagramme, pourtant il me semble que le 5V est uniquement là pour alimenter le board, pas pour alimenter un circuit externe, d'ailleurs on le branche bien en USB, ne faut-il pas plutôt utiliser le pin 3V3 ?~~

![image](https://github.com/xmow49/teleinfo-esphome-homeassistant/assets/1561084/fc2dd4c8-1db3-4f74-86cf-c85ec79caf05)
![image](https://github.com/xmow49/teleinfo-esphome-homeassistant/assets/1561084/5e6788dc-a0be-4d0c-b72e-8a3f6d66df3b)

Ma config, mon linky est tout neuf et donc en mode standard:
```
sphome:
  name: linky
  friendly_name: Linky

esp8266:
  board: d1_mini

logger:
  baud_rate: 0
  level: DEBUG
  esp8266_store_log_strings_in_flash: false

api:
  encryption:
    key: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

ota:
  password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  rx_pin: GPIO13
  tx_pin: GPIO1
  baud_rate: 9600
  parity: EVEN
  data_bits: 7

teleinfo:
  id: myteleinfo
  update_interval: 60s
  historical_mode: false

sensor:
  - platform: teleinfo
    tag_name: HCHC
    name: Linky HC
    teleinfo_id: myteleinfo
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: Wh
  - platform: teleinfo
    tag_name: HCHP
    name: Linky HP
    teleinfo_id: myteleinfo
    state_class: total_increasing
    device_class: energy
    unit_of_measurement: Wh
  - platform: teleinfo
    tag_name: PAPP
    name: Linky Consommation
    unit_of_measurement: VA
    icon: mdi:flash
    teleinfo_id: myteleinfo
  - platform: teleinfo
    tag_name: IINST
    name: Linky Intensité
    unit_of_measurement: A
    icon: mdi:flash
    teleinfo_id: myteleinfo
    
text_sensor:
  - platform: teleinfo
    tag_name: OPTARIF
    name: optarif
    teleinfo_id: myteleinfo
```

Edit: J'ai bien du 5V qui sort du pin 5V, on dirait que la doc que j'ai lu sur le D1 mini était fausse.
